---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: Splunk-Common
    image: pipseed/docker-centos7-ansible:latest 
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      deprecation_warnings: false
    ssh_connection:
      pipelining: True

verifier:
  name: ansible
